services:
  hexform-db-dev:
    container_name: hexform-db-dev 
    image: postgres:17
    env_file:
      - dev.env
    networks:
      - hexform_net_dev
    volumes:
      - ./database/data/dev:/var/lib/postgresql/data
    ports:
      - 5444:5432
  
  hexform-api:
    container_name: hexform-api 
    env_file:
      - dev.env
    networks:
      - hexform_net_dev
      - caddy_net
    build:
      context: ./
      dockerfile: ./API.Dockerfile

    ports:
      - 8020:8000


networks:
  hexform_net_dev:

  caddy_net:
    external: true
