
services:
  hexform-db:
    container_name: hexform-db 
    image: postgres:17
    env_file:
      - .env
    networks:
      - hexform_net
    volumes:
      - ./database/data/staging:/var/lib/postgresql/data
    
  hexform-api:
    container_name: hexform-api 
    env_file:
      - .env
    networks:
      - hexform_net
      - caddy_net
    build:
      context: ./
      dockerfile: ./API.Dockerfile

  networks:
  hexform_net:

  caddy_net:
    external: true
