"""add uk_users_username

Revision ID: 11068a8e0e08
Revises: 3077c3fa3ffc
Create Date: 2026-05-21 14:19:18.341154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11068a8e0e08'
down_revision: Union[str, Sequence[str], None] = '3077c3fa3ffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uk_users_username', 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uk_users_username', 'users', type_='unique')
    # ### end Alembic commands ###
