"""updata submission FK

Revision ID: 3ddb9277ed1e
Revises: 2b12cfbae8e8
Create Date: 2026-06-22 17:45:52.739071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ddb9277ed1e'
down_revision: Union[str, Sequence[str], None] = '2b12cfbae8e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('submissions_user_id_fkey'), 'submissions', type_='foreignkey')
    op.drop_constraint(op.f('submissions_survey_id_fkey'), 'submissions', type_='foreignkey')
    op.create_foreign_key(None, 'submissions', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'submissions', 'surveys', ['survey_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.create_foreign_key(op.f('submissions_survey_id_fkey'), 'submissions', 'surveys', ['survey_id'], ['id'])
    op.create_foreign_key(op.f('submissions_user_id_fkey'), 'submissions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
