"""add answers, survey_keys, submissions

Revision ID: 59208974f511
Revises: d932bd970ec6
Create Date: 2026-05-22 14:42:43.625745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59208974f511'
down_revision: Union[str, Sequence[str], None] = 'd932bd970ec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_keys',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('survey_id', sa.String(length=48), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value', name='uk_survey_key_value')
    )
    op.create_table('submissions',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('survey_id', sa.String(length=48), nullable=False),
    sa.Column('key_id', sa.String(length=48), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['key_id'], ['survey_keys.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'survey_id', name='uk_submissions')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submissions')
    op.drop_table('survey_keys')
    # ### end Alembic commands ###
