"""add survey & questions

Revision ID: 72c959daf63f
Revises: 11068a8e0e08
Create Date: 2026-05-22 11:26:54.100671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72c959daf63f'
down_revision: Union[str, Sequence[str], None] = '11068a8e0e08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveys',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.String(length=56), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('TEXT', 'NUMBER', 'RATING', 'BOOL', 'MULTI_PICK', name='type'), nullable=False),
    sa.Column('survey_id', sa.String(length=48), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.CheckConstraint('position >= 0', name='ck_questions_position'),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_table('surveys')
    # ### end Alembic commands ###
