"""update user_answers table

Revision ID: 9ca29a9dc12d
Revises: dc1499748787
Create Date: 2026-05-22 15:26:38.116745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ca29a9dc12d'
down_revision: Union[str, Sequence[str], None] = 'dc1499748787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anwers',
    sa.Column('id', sa.String(length=56), nullable=False),
    sa.Column('submission_id', sa.String(length=48), nullable=False),
    sa.Column('question_id', sa.String(length=56), nullable=False),
    sa.Column('answer_text', sa.String(length=5000), nullable=True),
    sa.Column('answer_number', sa.Float(), nullable=True),
    sa.Column('answer_bool', sa.Boolean(), nullable=True),
    sa.Column('answer_json', sa.JSON(), nullable=True),
    sa.CheckConstraint('answer_text IS NOT NULL OR answer_number IS NOT NULL OR answer_bool IS NOT NULL OR answer_json IS NOT NULL', name='ck_answer_at_least_one'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'question_id', name='uk_anwers')
    )
    op.drop_table('user_anwers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_anwers',
    sa.Column('id', sa.VARCHAR(length=56), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('submission_id', sa.VARCHAR(length=48), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.VARCHAR(length=56), autoincrement=False, nullable=False),
    sa.Column('answer_text', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('answer_number', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('answer_bool', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('answer_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.CheckConstraint('answer_text IS NOT NULL OR answer_number IS NOT NULL OR answer_bool IS NOT NULL OR answer_json IS NOT NULL', name=op.f('ck_answer_at_least_one')),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('user_anwers_question_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name=op.f('user_anwers_submission_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_anwers_user_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_anwers_pkey')),
    sa.UniqueConstraint('submission_id', 'question_id', name=op.f('uk_user_anwers'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('anwers')
    # ### end Alembic commands ###
