"""add survey state

Revision ID: d932bd970ec6
Revises: 72c959daf63f
Create Date: 2026-05-22 11:33:10.204938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd932bd970ec6'
down_revision: Union[str, Sequence[str], None] = '72c959daf63f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('state', sa.Enum('CREATED', 'PUBLISHED', 'DONE', name='type'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'state')
    # ### end Alembic commands ###
