"""update answer ck_answer_at_least_one

Revision ID: dc1499748787
Revises: 59208974f511
Create Date: 2026-05-22 14:57:41.302244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc1499748787'
down_revision: Union[str, Sequence[str], None] = '59208974f511'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_anwers',
    sa.Column('id', sa.String(length=56), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('submission_id', sa.String(length=48), nullable=False),
    sa.Column('question_id', sa.String(length=56), nullable=False),
    sa.Column('answer_text', sa.String(length=5000), nullable=True),
    sa.Column('answer_number', sa.Float(), nullable=True),
    sa.Column('answer_bool', sa.Boolean(), nullable=True),
    sa.Column('answer_json', sa.JSON(), nullable=True),
    sa.CheckConstraint('answer_text IS NOT NULL OR answer_number IS NOT NULL OR answer_bool IS NOT NULL OR answer_json IS NOT NULL', name='ck_answer_at_least_one'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'question_id', name='uk_user_anwers')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_anwers')
    # ### end Alembic commands ###
