"""reaname uk_answer constraint

Revision ID: f4e95b56f9da
Revises: ecefd6d9a858
Create Date: 2026-05-22 15:50:05.280971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4e95b56f9da'
down_revision: Union[str, Sequence[str], None] = 'ecefd6d9a858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uk_anwers'), 'answers', type_='unique')
    op.create_unique_constraint('uk_answers', 'answers', ['submission_id', 'question_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uk_answers', 'answers', type_='unique')
    op.create_unique_constraint(op.f('uk_anwers'), 'answers', ['submission_id', 'question_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
